### ISSUE TITLE
I want to make a DIY footswitch, I have some questions...

### ISSUE THREAD

**Issue by corechip** [joric/cc2540kbd#1]
Your project is very cool. I want to make a DIY footswitch like this, and a DIY keyboard maybe later.

Firstly, I'm searching for a bluetooth module. I have come across BC417, CC2540, CC2640, ESP32... What's the best module?
For a footswitch, I think the CC2540 is good. But for a keyboard with many keys, do I need other chips to work together with it? Are there anyother modules that can be used for a keyboard? And how to choose, which one is the best?

I also want the keyboard to have a function like the logitech's easy switch https://www.logitech.com/en-us/product/illuminated-keyboard-for-mac-ipad-iphone (using the same keyboard to pair with different computers and switch among them with one click). Can these modules do this?

Also, is it possible to change the key (winkey) easily? It appears I need to compile the firmware everytime if I want to change the key.

Lastly, you have the project for a year. How long the 3V battery last?

**Comment by corechip** [comment]
BTW, some of the CC2540 ones are even cheaper, just $1.45 but one of the oscillator is omitted. What's the oscillator is used for? Will that work for a keyboard? https://www.aliexpress.com/item/AT-09-Android-IOS-BLE-4-0-Bluetooth-module-for-arduino-CC2540-CC2541-Serial-Wireless-Module/32818178064.html

**Comment by joric** [comment]
@coreboot2 I have no idea about 3v battery, the project was disassembled a while ago, it's just a slightly modified CC254x SDK sample so it should be good. CC2541 and CC2540 are vastly different, CC2540 has USB hardware whlist CC2541 hasn't. It's basically just a HID sample from the SDK, so get the SDK, modify, compile, repeat.

There is a lot of other bluetooth modules you can flash into HID, check out my https://github.com/joric/bluetosis for example. Actually, nRF5x is better because the license is more relaxed and you don't need IAR to link the proprietary BT libs as with CC254x.

Maybe HC-06 (CSR-based) flashed into HID module with RN-42 firmware (google) is the cheapest and the easiest option, it only needs one Arduino Pro Micro (that you can also use as USB-TTL programmer) and one HC-06 module.
